server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:/tmp/sqlite/sso-database.db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          oidc:
            client-name:
            client-id: auth-code-mock-client
            client-secret: auth-code-mock-client-secret
            authorization-grant-type: authorization_code
            redirect_uri: https://mms5-test.jpl.nasa.gov/login/oauth2/code/oidc
            scope: openid,profile,email,offline_access
            provider: oidc
        provider:
          oidc:
            issuer-uri: http://localhost:8080
      resourceserver:
        jwt:
          issuer-uri: https://mms5-test.jpl.nasa.gov/

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

flexo:
  sso-auth-service:
    sso_user_id_field: ""
    jwt_user_id_field: ""
    group_claims_field: "groups"
  sparql:
    query-url: "http://localhost:3030/ds/sparql"
    update-url: "http://localhost:3030/ds/update"
    graph-store-protocol-url: "http://localhost:3030/ds/data"
    root-context: "http://layer1-service"

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE