server:
  port: 3000
  servlet:
    context-path: /sso
spring:
  datasource:
    url: jdbc:sqlite:sso-database.db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          oidc:
            client-name:
            client-id: auth-code-mock-client
            client-secret: auth-code-mock-client-secret
            authorization-grant-type: authorization_code
            redirect_uri: http://localhost:3000/sso/login/oauth2/code/oidc
            scope: openid,profile,email
        provider:
          oidc:
            issuer-uri: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

flexo:
  sso-auth-service:
    sso_user_id_field: "sid"
    jwt_user_id_field: "sid"
    group_claims_field: "groups"

jwt:
  domain: ${JWT_DOMAIN:https://jwt-provider-domain/}
  audience: ${JWT_AUDIENCE:jwt-audience}
  realm: ${JWT_REALM:Flexo MMS Microservices}
  secret: ${JWT_SECRET:somethingreallyreallylong}
  duration: ${JWT_DURATION:86400000}

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.openmbee.flexo.mms.sso: INFO